### ISSUE TITLE
How does this compare to executing CGSession -suspend?

### ISSUE THREAD

**Issue by davidosomething** [sindresorhus/lock-system#2]
i.e., https://github.com/unixorn/tumult.plugin.zsh/blob/master/bin/lockscreen

is suspension different from SAC lock?

**Comment by sindresorhus** [comment]
See: https://twitter.com/mkuehnel/status/897164211075391488

<img width="633" alt="screen shot 2017-08-15 at 17 06 19" src="https://user-images.githubusercontent.com/170270/29321882-16de99ca-81dc-11e7-94a5-9a504bc64ece.png">
