### ISSUE TITLE
Provide source for macOS lock-binary or implement different method

### ISSUE THREAD

**Issue by ameesme** [sindresorhus/lock-system#4]
The macOS lock-executable's source is currently not provided in the repository. Perhaps this could be added.

An alternative solution that doesn't require a binary would be to use `child-process` to execute the `pmset displaysleepnow` command. This will put the screen to sleep, which results in a lock if the user has set a log-in password and turned on "Require password after sleep or screen saver begins" in System Preferences, which should be the case anyway.

## Example code
```
const { exec } = require('child_process');
exec('pmset displaysleepnow');
```

**Comment by sindresorhus** [comment]
> The macOS lock-executable's source is currently not provided in the repository

The source is linked to in the code: https://github.com/sindresorhus/lock-system/blob/6e158438108f0a5e23e69fbe582f02da1b721906/index.js#L31

> An alternative solution that doesn't require a binary would be to use child-process to execute the pmset displaysleepnow command.

https://twitter.com/sindresorhus/status/897103870429716481

**Comment by ameesme** [comment]
Ah, missed that line. Thanks for the heads up!
