### ISSUE TITLE
Put `cinnamon-screensaver-command` first?

### ISSUE THREAD

**Issue by Fleker** [sindresorhus/lock-system#7]
Hey, is there a particular reason for the order of Linux commands? The way that it's currently set, it actually doesn't work for me. My workstation seems to have xdg-screensaver, but no-ops when I try to run the command. The cinnamon command works.

**Comment by sindresorhus** [comment]
No idea, to be honest. I don't use Linux. Linux support was contributed by @stevelacy. Maybe he knows.

**Comment by stephenlacy** [comment]
@Fleker Run the `xdg-screensaver` command in your terminal, you may a version that does not accept the same arguments.

**Comment by Fleker** [comment]
```
me@me:~$ xdg-screensaver
xdg-screensaver - command line tool for controlling the screensaver

Synopsis

xdg-screensaver suspend WindowID

xdg-screensaver resume WindowID

xdg-screensaver { activate | lock | reset | status }

xdg-screensaver { --help | --manual | --version }

Use 'man xdg-screensaver' or 'xdg-screensaver --manual' for additional info.
me@me:~$ xdg-screensaver --version
xdg-screensaver 1.1.3

```

**Comment by stephenlacy** [comment]
Does `xdg-screensaver lock` do anything?

**Comment by Fleker** [comment]
The command executes, but nothing happens.

**Comment by stephenlacy** [comment]
The issue is with your os configuration for xdg and not this project.

**Comment by Fleker** [comment]
Ok.
